language: node_js
node_js:
  - 6.9.4
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: colbywhite@users.noreply.github.com
  api_key:
    secure: tqujFk8xBCG30+f6mY7UPoMhBITcZJwKrvPKNrO25mlQWeiUtnouvWbYDa3fMRCbjKMoRFc8Oa0jh1Tg/EqAo0W6hj9mTVhI7F8hQ+IlpvDmy46M2P65e8UwjABCeTnPMwo0/juNt/fIbjjJMZhbPsKlDl0TCXtPAM5apNe9qg6I4jwlFtPJLWyH+0naZYAEgK5LQYBClQuZ7dRrN0tEs5gHKT/x/GAISd3249Zulqc2IUiIrUGktm9qqIR5IvZz+ztHHWW92Ev+l8GBbPiPS3XCAIfu8yTWcM3JE/d4igO6eQYvQqnb4CAXhSm1PaK3gkjcinxPElAJ3v93epK2k5UiZyAxSlaCrrkVu6MDhCuouPnuMMXxOr+KWbkt8gZq01cl9XUy/tMJXaA2U52lQDdib0J52/jEJBMYEZEGZwPa7Nkt500uONDEKIkGn+Uj55CeblyRsX7izIzl6ssw3ghixiDHlbdk09tFQeQ/317KoczBmAAQTZPaXS2M4/8R429DsjWwpTNzmieclOtsot8Q3t0nCxKv8CIvZz2fgcejgv/4DpmreIbexcTstiZtd8nbJLb3Sap09MLVA6hxBp31QH8GRvbFhIEGvRTN1sTBK1msRw7i7zYRItIRPP527WiKMwhWHeXmFzI99oBtmBiv4UYrihGC+NJaWme6dDg=
  on:
    tags: true
    repo: colbywhite/aws-cf-monitor
