language: node_js
node_js:
- lts/dubnium
cache:
  directories:
  - node_modules
before_deploy: npm run build
deploy:
  provider: npm
  email: colbywhite@users.noreply.github.com
  skip_cleanup: true
  api_key:
    secure: JRG75+RPSffia7ChrHpRMgUTKkatNwb5HHL3oDt2Wb14AGU+2rJXtCKM+Xha7DxOyB5d/rT8LZ/tglNrfFCmNM2q6Y5n0GSpxJ8nNC6ZBrcI0Nl8ioYDUiX7NtbFNBWrDOoJdnduzFQT1KOWBSNrpjw3mb2e/qlBr7In4yK/qo2bh31PJXoALSSKYdZkzJd8W0yVPqTqh07QyIrhAJccWe7c4Y8KAuNRQr1k/EElVVOZXynVHBtqpPXDgk81q/IfkhVHxQxwc3MXs81iwA4UYr15q6tFaTn2lb8v1hU/L6ECrTcpzSFayBASWWpyvIGOpwutGbihEcPudao3Rgt0PIfoVHUsu2lnn5OE/pa1sV26fFW6poqh0E+EHHRjXkj9AIGIUXFZuzVCne2MIDYgWgtaQ0kVsIoovVv0pWj5dknd4X32u5DG0KYR4gkUVonChVtDaTfD7v8XwiQbnug3L2Yu6FvmJuB5oYcecRGg0EgxjlH5JN+zmATZvesmkoa3GEJpxnNjll+hDnMF1HnXogTG4QdDH+/K/kzisSndZgP6AK6j6rU/25l8nSTzMiVvNR0KuG7D2sMzpe8aCRWDLu9alkXoZRprri53zvfTT7Ag+UDVpqH5E37D0z5CfPOGikorGO5/9TQqUDZemes7jJAcKCkOTjHa6CuRuF3XETw=
  on:
    tags: true
    repo: colbywhite/aws-cf-monitor
